models/User.php
<?php

namespace app\models;


use app\helpers\God;
use Yii;
use yii\base\NotSupportedException;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

/**
 * @property string id
 * @property string email
 * @property string hash
 * @property string auth
 * @property string code
 * @property number account
 * @property string password
 * @property string referral_id
 * @property string surname
 * @property string forename
 *
 * @property User referral
 */
class User extends ActiveRecord implements IdentityInterface {

    private $_password;
    public $repeat;

    const LOGIN = '/^[a-z][\w\.]{3,22}\w$/';
    const PERFECT = '/^U\d{7,8}$/';

    public static function tableName()
    {
        return 'user';
    }

    public static function primaryKey() {
        return ['id'];
    }

    public function rules() {
        return [
            [['id', 'email', 'referral_id', 'forename', 'surname', 'perfect_usd'], 'required'],
//            [['password', 'repeat'], 'required', 'on' => 'signup'],
            ['id', 'string'],
            ['email', 'email'],
            [['hash', 'auth', 'code'], 'string'],
            [['id', 'referral_id'], 'match', 'pattern' => static::LOGIN],
            ['account', 'default', 'value' => 0],
            ['id', 'unique',
                'targetClass' => 'app\models\User',
                'message' => Yii::t('app', 'This value has already been taken')],
            ['referral_id', 'exist',
                'targetClass' => 'app\models\User',
                'targetAttribute' => 'id',
                'message' => Yii::t('app', 'The referral does not exists')],
            ['perfect_usd', 'match', 'pattern' => static::PERFECT],
        ];
    }
/*
    public function scenarios()
    {
        return [
            'default' => ['id', 'email', 'password', 'referral_id', 'wallet_perfect'],
            'update' => ['email'],
        ];
    }
*/
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'Login'),
            'account' => Yii::t('app', 'Account'),
            'email' => Yii::t('app', 'Email'),
            'hash' => Yii::t('app', 'Hash'),
            'auth' => Yii::t('app', 'Auth'),
            'code' => Yii::t('app', 'Code'),
            'referral_id' => Yii::t('app', 'Referral Login'),
            'forename' => Yii::t('app', 'First Name'),
            'surname' => Yii::t('app', 'Last Name'),
            'perfect_usd' => Yii::t('app', 'Perfect Money USD wallet'),
        ];
    }

    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getAuthKey()
    {
        return static::hashAuthKey($this->auth);
    }

    public function validateAuthKey($authKey)
    {
        return static::hashAuthKey($this->auth) == $authKey;
    }

    protected static function hashAuthKey($key)
    {
        $ip = Yii::$app->request->getUserIP();
        if ($ip) {
            $key .= 'devil' . $ip;
        }
        return hash('sha512', $key);
    }

    public function generateAuthKey() {
        $this->auth = Yii::$app->security->generateRandomString(64);
    }

    public function generateCode() {
        $this->code = Yii::$app->security->generateRandomString(64);
    }

    public function setPassword($value) {
        if (!password_verify($value, $this->hash)) {
            $this->_password = $value;
            $this->hash = password_hash($value, PASSWORD_DEFAULT);
            $this->generateAuthKey();
        }
    }

    public function getPassword() {
        return $this->_password;
    }

    public function validatePassword($value) {
        return password_verify($value, $this->hash);
    }

    public function dumpErrors() {
        foreach($this->getErrors() as $name => $message) {
            Yii::$app->session->addFlash($name . ': ' . $message);
        }
    }

    public function sendEmail($params, $template = 'basic') {
        return God::mail($this->email, $template, $params);
    }

    public function getReferral() {
        return $this->hasOne(static::className(), ['id' => 'referral_id']);
    }

    public function walletAttributes() {
        return ['perfect_usd'];
    }
}

controllers/UserController.php
<?php

namespace app\controllers;


use app\helpers\SQL;
use app\models\LoginForm;
use app\models\PasswordForm;
use app\models\RequestForm;
use app\models\User;
use app\models\WalletForm;
use app\modules\pyramid\models\Node;
use kartik\base\Config;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

class UserController extends Controller {
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'create', 'update', 'login', 'logout', 'request', 'reset', 'password', 'reset-auth'],
                'rules' => [
                    [
                        'actions' => ['create', 'login', 'request', 'reset'],
                        'allow' => true,
                        'roles' => ['?']
                    ],
                    [
                        'actions' => ['logout', 'update', 'password'],
                        'allow' => true,
                        'roles' => ['@']
                    ],
                    [
                        'actions' => ['index', 'reset-auth'],
                        'allow' => true,
                        'roles' => ['admin']
                    ],
                ]
            ]
        ];
    }

    public function actionIndex($referral_id = null) {
        return $this->render('index', [
            'dataProvider' => new ActiveDataProvider([
                'query' => User::find()->andFilterWhere(['referral_id' => $referral_id]),
                'sort' => [
                    'defaultOrder' => ['id' => SORT_DESC]
                ]
            ])
        ]);
    }
    public function actionUnblock($user_id){
        $pillow = \app\models\Config::get('common','pillow');
        \app\models\Config::set('common','pillow',(float)$pillow +2);
        $type = Node::find()->where(['user_id'=>$user_id])->select('type_id')->scalar();
        $node = Node::find()->andWhere(['type_id'=>$type])->select('max(number)')->scalar();
        SQL::execute('UPDATE "node" SET "number" = :nmb WHERE "user_id" = :uid',[
            ':nmb'=>$node+1,
            ':uid'=>$user_id
        ]);
        SQL::execute('UPDATE "user" SET "time" = now() WHERE "id" = :uid',[
            ':uid'=>$user_id
        ]);
        return $this->redirect('index');
    }

    public function actionLogin() {
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = $model->getUser();
            if ($user && $user->validatePassword($model->password)) {
                $node = new Node();
                $node = $node->find()->where(['user_id'=>$user->id])->one();
                if($node) {
                    if ($node->number == null) {
                        return $this->render('block');
                    }
                }
                if (empty($user->auth)) {
                    $user->generateAuthKey();
                    $user->save(true, ['auth']);
                }
                if (Yii::$app->user->login($user)) {
                    return $this->redirect(['view', 'id' => $user->id]);
                }
            }
            else {
                Yii::$app->session->setFlash('error', Yii::t('app', 'Invalid username or password'));
            }
        }

        return $this->render('login', [
            'model' => $model
        ]);
    }

    public function actionLogout($destroy = false) {
        Yii::$app->user->logout($destroy);
        return $this->goHome();
    }

    public function actionResetAuth($id) {
        if (!Yii::$app->user->can('manage')) {
            if ($id != Yii::$app->user->id) {
                throw new ForbiddenHttpException();
            }
            Yii::$app->layout = 'cabinet';
        }
        $model = $this->findModel($id);
        $model->generateAuthKey();
        if ($model->save(false)) {
            Yii::$app->session->addFlash('success', Yii::t('app', 'Logout done'));
        }
        return $this->goHome();
    }

    public function actionCreate($referral_id = null) {
        $model = new User(['referral_id' => $referral_id]);
        Yii::$app->view->title = Yii::t('app', 'Signup');
        return $this->edit($model);
    }

    public function actionUpdate($id = null) {
        if (!Yii::$app->user->can('manage')) {
            Yii::$app->layout = 'cabinet';
        }
        $model = $this->findModel($id);
        Yii::$app->view->title = Yii::t('app', 'Update');
        return $this->edit($model);
    }

    public function actionView($id = null) {
        if (empty($id)) {
            return $this->redirect(['user/view', 'id' => Yii::$app->user->id]);
        }
        if (!Yii::$app->user->can('manage')) {
            Yii::$app->layout = 'cabinet';
        }
        $model = $this->findModel($id);
        return $this->render('view', [
            'model' => $model
        ]);
    }

    public function findModel($id = null) {
        /** @var User $model */
        if ($id) {
            $model = User::findOne($id);
            if (!$model) {
                throw new NotFoundHttpException();
            }
        }
        else {
            $model = Yii::$app->user->identity;
        }
        return $model;
    }

    public function actionPassword($id) {
        if (!Yii::$app->user->can('manage')) {
            if ($id != Yii::$app->user->id) {
                throw new ForbiddenHttpException();
            }
            Yii::$app->layout = 'cabinet';
        }
        $user = $this->findModel($id);
        $model = new PasswordForm();
        if ($this->password($user, $model)) {
            return $this->redirect(['view', 'id' => $id]);
        }
        return $this->render('password', [
            'model' => $model
        ]);
    }

    public function actionReset($code) {
        /** @var User $user */
        $user = User::findOne(['code' => $code]);
        if (!$user) {
            Yii::$app->session->addFlash('error', Yii::t('app', 'Invalid code'));
            return $this->goHome();
        }
        $model = new PasswordForm();
        $user->code = null;
        if ($this->password($user, $model)) {
            return $this->redirect(['login']);
        }
        return $this->render('password', [
            'model' => $model
        ]);
    }

    public function actionRequest() {
        $model = new RequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = $model->getUser();
            if ($user) {
                $user->generateCode();
                if ($user->save(false)) {
                    $url = Url::to(['reset', 'code' => $user->code], true);
                    $content = Yii::t('app', 'To recover your password, open <a href="{url}">this link</a>', [
                        'url' => $url,
                    ]);
                    $user->sendEmail([
                        'subject' => Yii::$app->name . ': ' . Yii::t('app', 'Password reset'),
                        'content' => $content
                    ]);
                    Yii::$app->session->addFlash('info', Yii::t('app', 'Check your mail'));
                    return $this->goHome();
                }
            }

            if (empty($model->id) && empty($model->email)) {
                Yii::$app->session->addFlash('error', Yii::t('app', 'Enter login or email'));
            }
        }

        return $this->render('request', [
            'model' => $model
        ]);
    }

    public function actionWallet($id) {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save(true, $model->walletAttributes())) {
            return $this->redirect(['view', 'id' => $id]);
        }
        return $this->render('wallet', [
            'model' => $model
        ]);
    }

    protected function edit(User $model) {
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->save(false) && Yii::$app->user->login($model)) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }
        return $this->render('edit', [
            'model' => $model
        ]);
    }

    protected function password(User $user, PasswordForm $model) {
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user->setPassword($model->password);
            return $user->save(true, ['hash', 'auth', 'code']);
        }
        return false;
    }
}

views/user/block.php
<?php
/**
 * Created by PhpStorm.
 * User: yura
 * Date: 27.01.16
 * Time: 18:16
 */
$this->title = 'Account blocked';
?>
<div class="alert alert-danger" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="sr-only">Error:</span>
    <?=Yii::t('app','Profile blocked') ?>, <a href="/feedback/create/"><?=Yii::t('app','contact admin')?></a>.
</div>

views/user/edit.php
<?php
/* @var $this yii\web\View */
/* @var $model \app\models\User */

use app\models\User;
use app\widgets\Fake;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

if ($model->hasErrors()) {
    echo Html::script('var errors = ' . json_encode($model->getErrors()));
}

?>
<div class="user-edit">
    <?php
    $form = ActiveForm::begin([
        'options' => ['name' => 'User']
    ]);
    ?>

    <p>
        <?= Fake::widget() ?>
    </p>
    <div>
        <?php if(Yii::$app->controller->action->id == "create") {
            echo $form->field($model, 'referral_id');
            echo $form->field($model, 'id');
        }?>
        <?= $form->field($model, 'email') ?>
        <?php if(Yii::$app->controller->action->id == "create") {
            echo $form->field($model, 'account');
            echo $form->field($model, 'perfect_usd');
        }?>
        <?= $form->field($model, 'surname') ?>
        <?= $form->field($model, 'forename') ?>
        <?= $form->field($model, 'password')->passwordInput() ?>
        <?= $form->field($model, 'repeat')->passwordInput() ?>
    </div>

    <p>
        <?php if(Yii::$app->controller->action->id == "create") { ?>
        <input type="checkbox" id="agree" />
        <label for="agree">я согласен с условиями компании</label>
        <?php } ?>
    </p>

    <p>
        <?= Html::submitButton($this->title, ['class' => 'btn btn-primary']) ?>
    </p>

    <?php ActiveForm::end(); ?>
</div>

views/user/index.php
<?php

use app\helpers\SQL;
use app\models\User;
use app\modules\pyramid\models\Node;
use yii\grid\GridView;
use yii\helpers\Html;

/** @var $this yii\web\View */
/** @var \yii\data\ActiveDataProvider $dataProvider */
$this->title = Yii::t('app','Users');
?>
<div class="user-index">
    <p>
        <?= Html::a(Yii::t('app', 'Create'), ['/admin/user/create']) ?>
    </p>

    <?=  GridView::widget([
        'dataProvider' => $dataProvider,
        'rowOptions'=>function($data){
            $node = new Node();
            $node = $node->find()->where(['user_id'=>$data->id, 'number'=>null])->one();
            if($node){
                return ['class'=>'danger'];
            }
        },
        'columns' => [
            [
                'attribute' => 'id',
                'format' => 'html',
                'value' => function(User $model) {
                    return Html::a($model->id, ['view', 'id' => $model->id]);
                }
            ],
            'surname',
            'forename',
            'email',
            'account',
            'perfect_usd',
            [
                'attribute' => 'referral_id',
                'format' => 'html',
                'value' => function(User $model) {
                    return Html::a($model->referral_id, ['index', 'referral_id' => $model->referral_id]);
                }
            ],
            [
//                'label' => Yii::t('app', 'Actions'),
//                'attribute' => 'id',
                'format' => 'html',
                'value' => function(User $model) {
                    $items = [
                        Html::a(' ', ['update', 'id' => $model->id], [
                            'class' => 'fa fa-pencil-square-o',
                            'title' => Yii::t('app', 'Edit')
                        ])
                    ];
                    if ($model->auth) {
                        $items[] = Html::a('', ['/admin/user/login', 'auth' => $model->auth], [
                            'class' => 'fa fa-sign-in',
                            'title' => Yii::t('app', 'Login')
                        ]);
                    }
                    $node = new Node();
                    $node = $node->find()->where(['user_id'=>$model->id, 'number'=>null])->one();
                    if($node){
                        $items[] = Html::a('', ['/user/unblock', 'user_id'=>$model->id], [
                            'class' => 'glyphicon glyphicon-expand',
                            'title' => Yii::t('app', 'Unblock')
                        ]);
                    }
                    return implode(' ', $items);
                }
            ],
        ]

    ]) ?>
</div>

views/user/login.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\LoginForm */
/* @var $form ActiveForm */

$this->title = Yii::t('app', 'Login');
?>
<div class="user-login">
    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name') ?>
    <?= $form->field($model, 'password')->passwordInput() ?>

    <p>
        <?= Html::submitButton($this->title) ?>
    <p>
    <?php ActiveForm::end(); ?>
</div><!-- user-login -->

views/user/password.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
/** @var \app\models\PasswordForm $model */
?>
<div class="user-reset">
    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'password')->passwordInput() ?>
    <?= $form->field($model, 'repeat')->passwordInput() ?>
    <?= Html::submitButton(Yii::t('app', 'Change')) ?>
    <?php ActiveForm::end() ?>
</div>

views/user/request.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
/** @var \app\models\RequestForm $model */
?>
<div class="user-request">
    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'id') ?>
    <?= $form->field($model, 'email') ?>
    <?= Html::submitButton(Yii::t('app', 'Send Password')) ?>
    <?php ActiveForm::end() ?>
</div>

views/user/view.php
<?php
/* @var $this yii\web\View */
/* @var $model \app\models\User */

use omnilight\assets\MomentAsset;
use omnilight\assets\MomentLanguageAsset;
use yii\helpers\Html;
use yii\widgets\DetailView;

MomentAsset::register($this);
MomentLanguageAsset::register($this);

$this->title = $model->id;

function spaces() {
    return implode(' ', func_get_args());
}

if (Yii::$app->user->can('manage')) {
    $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
}

$time = strtotime($model->time);
?>
<div class="user-view">
    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id]) ?>
        <?= Html::a(Yii::t('app', 'Password'), ['password', 'id' => $model->id]) ?>
        <?= Html::a(Yii::t('app', 'Invoices'), ['/invoice/index', 'user_id' => $model->id]) ?>
        <?= Html::a(Yii::t('app', 'Investments'), ['/pyramid/node/index', 'user_id' => $model->id]) ?>
    </p>

    <div class="attributes">
        <?= Html::tag('h2', $model->id) ?>
        <?= Html::tag('h3', spaces($model->forename, $model->surname)) ?>

        <?=Yii::t('app','Deductions')?> <?= Html::tag('span', date('Y-m-d H:i', $time), [
            'id' => 'last',
            'data-time' => $time,
            'data-left' => $time + 3600 * 24 * 7,
        ]) ?>

        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                [
                    'attribute' => 'account',
                    'value' => (float) $model->account
                ],
                [
                    'attribute' => 'referral_id',
                    'format' => 'html',
                    'value' => Html::a($model->referral_id,
                        ['view', 'referral_id' => $model->referral_id],
                        ['class' => 'value'])
                ],
                'email',
            ]
        ]) ?>
    </div>
</div>

views/user/wallet.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$users_url = ['label' => Yii::t('app', 'Users')];
if (Yii::$app->user->can('manage')) {
    $users_url['url'] = ['index'];
}
$this->params['breadcrumbs'][] = $users_url;
$this->params['breadcrumbs'][] = ['label' => Yii::$app->user->id, 'url' => ['view', 'id' => Yii::$app->user->id]];

/** @var \app\models\User $model */
?>
<div class="user-wallet">
    <?php $form = ActiveForm::begin(); ?>

    <?php
    foreach($model->walletAttributes() as $name) {
        echo $form->field($model, $name);
    }
    ?>

    <?= Html::submitButton(Yii::t('app', 'Save')) ?>

    <?php ActiveForm::end(); ?>
</div>